
const ADMIN_ACCESS_CODE="ADMINDEUS1";
const SPREADSHEET_ID="1FCV9ca7XdwW2ZnJICq65kRme5fAXaAVURsQKPdOHV90";
const APP_SCRIPT_URL="https://script.google.com/macros/s/AKfycbx739xcgwZ0NTYdtj0pjFN0QAqyNh94PV96PxKRy90pOvKHOg1V0LFf-gjkrIsKaL1w/exec";
const SHEETS={usuarios:"usuarios",empresas:"empresas",entregas:"entregas",entregadores:"entregadores",mensagens:"mensagens",saques:"saques"};
let db={usuarios:[],empresas:[],entregas:[],entregadores:[],mensagens:[],saques:[]};let currentDeliveryExport=[];let currentDriverSummary=null;let currentPayWithdrawId="";let deliveryNotifications=[];let alertAudioCtx=null;let alertSoundTimer=null;let dashboardAutoTimer=null;let dashboardLoading=false;
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}function num(v){if(typeof v==="number")return v;return Number(String(v||"0").replace(/\./g,"").replace(",",".").replace(/[^0-9.-]/g,""))||0}function norm(v){return String(v==null?"":v).trim()}function lower(v){return norm(v).toLowerCase()}function onlyDigits(v){return String(v||"").replace(/\D/g,"")}function escapeHtml(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}function showLoader(t){document.getElementById("loaderText").innerText=t||"Carregando...";document.getElementById("loader").classList.add("active")}function hideLoader(){document.getElementById("loader").classList.remove("active")}function showStatus(text,type){const el=document.getElementById("statusBox");el.innerText=text;el.className="status-box active "+(type||"");setTimeout(()=>el.classList.remove("active"),6500)}
function loginAdmin(){const code=norm(document.getElementById("adminCode").value).toUpperCase();if(code!==ADMIN_ACCESS_CODE){alert("Código de acesso administrativo inválido.");return}localStorage.setItem("pegaleva_admin_access","1");document.getElementById("loginScreen").style.display="none";document.getElementById("appScreen").classList.add("active");setToday();unlockAlertAudio();loadDashboard(true);startDashboardAutoUpdate()}function logoutAdmin(){stopDashboardAutoUpdate();localStorage.removeItem("pegaleva_admin_access");document.getElementById("appScreen").classList.remove("active");document.getElementById("loginScreen").style.display="flex";document.getElementById("adminCode").value=""}if(localStorage.getItem("pegaleva_admin_access")==="1"){document.getElementById("loginScreen").style.display="none";document.getElementById("appScreen").classList.add("active");setToday();loadDashboard(true);startDashboardAutoUpdate()}
function todayISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function setToday(){document.getElementById("salesDate").value=todayISO();renderAll()}
async function loadDashboard(showVisual){if(dashboardLoading)return;dashboardLoading=true;if(showVisual)showLoader("Conectando à planilha...");try{const result=await Promise.all([loadSheet(SHEETS.usuarios),loadSheet(SHEETS.empresas),loadSheet(SHEETS.entregas),loadSheet(SHEETS.entregadores),loadSheet(SHEETS.mensagens),loadSheet(SHEETS.saques)]);db={usuarios:result[0],empresas:result[1],entregas:result[2],entregadores:result[3],mensagens:result[4],saques:result[5]};checkNewDeliveries();fillStatusFilter();renderAll();renderChatNotifications();document.getElementById("lastUpdate").innerText="Conectado à planilha • Atualizado em "+new Date().toLocaleString("pt-BR");if(showVisual)showStatus("Dashboard atualizado com sucesso.","green")}catch(err){if(showVisual)showStatus((err&&err.message?err.message:String(err))||"Erro ao carregar dados.","red")}finally{dashboardLoading=false;if(showVisual)hideLoader()}}
function startDashboardAutoUpdate(){stopDashboardAutoUpdate();dashboardAutoTimer=setInterval(()=>loadDashboard(false),2000)}
function stopDashboardAutoUpdate(){if(dashboardAutoTimer){clearInterval(dashboardAutoTimer);dashboardAutoTimer=null}}
async function loadSheet(sheetName){const url=`https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheetName)}&_t=${Date.now()}`;const res=await fetch(url);if(!res.ok)throw new Error("Não foi possível ler a aba "+sheetName+". Publique/compartilhe a planilha para leitura ou confira o nome da aba.");const csv=await res.text();return parseCSV(csv)}
function parseCSV(csv){const rows=[];let row=[],cur="",q=false;for(let i=0;i<csv.length;i++){const c=csv[i],n=csv[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===","&&!q){row.push(cur);cur="";continue}if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&n==="\n")i++;row.push(cur);cur="";if(row.some(v=>norm(v)!==""))rows.push(row);row=[];continue}cur+=c}row.push(cur);if(row.some(v=>norm(v)!==""))rows.push(row);if(!rows.length)return[];const headers=rows.shift().map(h=>norm(h));return rows.map(r=>{const obj={};headers.forEach((h,i)=>obj[h]=r[i]!==undefined?r[i]:"");return obj})}
function parseDate(v){if(!v)return null;if(Object.prototype.toString.call(v)==="[object Date]"&&!isNaN(v.getTime()))return v;const s=norm(v);let m=s.match(/^(\d{4})-(\d{2})-(\d{2})(?:[ T](\d{2}):(\d{2}):(\d{2}))?/);if(m)return new Date(Number(m[1]),Number(m[2])-1,Number(m[3]),Number(m[4]||0),Number(m[5]||0),Number(m[6]||0));m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})(?:[ T](\d{2}):(\d{2}):(\d{2}))?/);if(m)return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]||0),Number(m[5]||0),Number(m[6]||0));const d=new Date(s);return isNaN(d.getTime())?null:d}function dateISO(v){const d=parseDate(v);if(!d)return"";return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function dateBR(v){const d=parseDate(v);if(!d)return escapeHtml(v);return d.toLocaleString("pt-BR")}
function fillStatusFilter(){const sel=document.getElementById("deliveryStatusFilter");const current=sel.value;const statuses=[...new Set(db.entregas.map(d=>norm(d.Status)).filter(Boolean))].sort();sel.innerHTML='<option value="">Todos os status</option>'+statuses.map(s=>`<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join("");sel.value=current}
function renderAll(){renderBankCard();renderKpis();renderFinanceSummary();renderStatusSummary();renderDeliveries();renderUsers();renderCompanies();renderDrivers();renderMessages()}function isClosed(d){return["Entrega finalizada","Cancelada","Cancelada Geral"].includes(norm(d.Status))}function isPaid(d){return lower(d.StatusPagamento)==="pago"}function isPending(d){const p=lower(d.StatusPagamento);return p==="pendente"||p==="aguardando confirmação"||!p}
function renderBankCard(){const selected=document.getElementById("salesDate").value||todayISO();const todayList=db.entregas.filter(d=>dateISO(d.CriadoEm||d.AtualizadoEm)===selected);const todayRevenue=todayList.reduce((s,d)=>s+num(d.Valor),0);const paidToday=todayList.filter(isPaid).reduce((s,d)=>s+num(d.Valor),0);const pendingToday=todayList.filter(isPending).reduce((s,d)=>s+num(d.Valor),0);document.getElementById("todayRevenue").innerText=money(todayRevenue);document.getElementById("todaySales").innerText=todayList.length;document.getElementById("todayInfo").innerText=`Pago: ${money(paidToday)} • Pendente/Aguardando: ${money(pendingToday)}`}
function driverFinancial(d){const list=driverDeliveries(d).filter(e=>norm(e.Status)==="Entrega finalizada"&&(isPaid(e)||isPending(e)));const total=list.reduce((sum,e)=>sum+num(e.Valor),0);const taxa=list.length*1.98;const liquido=Math.max(0,total-taxa);const pago=(db.saques||[]).filter(s=>lower(s.Status)==="pago"&&norm(s.CodigoEntregador)===norm(d.CodigoAcesso)).reduce((sum,s)=>sum+num(s.ValorSolicitado),0);const saldo=Math.max(0,liquido-pago);return{entregas:list.length,total,taxa,liquido,pago,saldo}}
function allDriversFinancial(){return db.entregadores.map(driverFinancial).reduce((acc,f)=>{acc.entregas+=f.entregas;acc.total+=f.total;acc.taxa+=f.taxa;acc.liquido+=f.liquido;acc.pago+=f.pago;acc.saldo+=f.saldo;return acc},{entregas:0,total:0,taxa:0,liquido:0,pago:0,saldo:0})}
function renderKpis(){const totalRevenue=db.entregas.reduce((s,d)=>s+num(d.Valor),0);const pending=db.entregas.filter(isPending).reduce((s,d)=>s+num(d.Valor),0);const running=db.entregas.filter(d=>!isClosed(d)).length;const done=db.entregas.filter(d=>norm(d.Status)==="Entrega finalizada").length;const activeDrivers=db.entregadores.filter(d=>lower(d.Ativo)==="ativo").length;const df=allDriversFinancial();document.getElementById("kpiTotalRevenue").innerText=money(totalRevenue);document.getElementById("kpiDriverFees").innerText=money(df.taxa);document.getElementById("kpiDriverNet").innerText=money(df.saldo);document.getElementById("kpiPending").innerText=money(pending);document.getElementById("kpiDeliveries").innerText=db.entregas.length;document.getElementById("kpiRunning").innerText=running;document.getElementById("kpiDone").innerText=done;document.getElementById("kpiUsers").innerText=db.usuarios.length;document.getElementById("kpiCompanies").innerText=db.empresas.length;document.getElementById("kpiActiveDrivers").innerText=activeDrivers}
function renderFinanceSummary(){const totalEntregas=db.entregas.reduce((s,d)=>s+num(d.Valor),0);const pagas=db.entregas.filter(isPaid).reduce((s,d)=>s+num(d.Valor),0);const pendentes=db.entregas.filter(isPending).reduce((s,d)=>s+num(d.Valor),0);const df=allDriversFinancial();const saldoEmpresas=db.empresas.reduce((s,e)=>s+num(e.SaldoDevedor),0);const pagoUsuarios=db.usuarios.reduce((s,u)=>s+num(u.ValorPago),0);const pagoEmpresas=db.empresas.reduce((s,e)=>s+num(e.ValorPago),0);const pendUsuarios=db.usuarios.reduce((s,u)=>s+num(u.PagamentoPendente),0);const pendEmpresas=db.empresas.reduce((s,e)=>s+num(e.PagamentoPendente),0);const rows=[["Valor total em entregas",money(totalEntregas),"money"],["Entregas pagas",money(pagas),"money green"],["Entregas pendentes/aguardando",money(pendentes),"money red"],["Bruto finalizado dos entregadores",money(df.total),"money"],["Taxa sistema/serviço dos entregadores (pagas e pendentes)",money(df.taxa),"money red"],["Saldo líquido a transferir aos entregadores",money(df.saldo),"money green"],["Saques já pagos aos entregadores",money(df.pago),"money green"],["Valor pago por usuários",money(pagoUsuarios),"money green"],["Valor pago por empresas",money(pagoEmpresas),"money green"],["Pendente usuários",money(pendUsuarios),"money red"],["Pendente empresas",money(pendEmpresas),"money red"],["Saldo devedor empresas",money(saldoEmpresas),"money red"]];document.getElementById("financeSummary").innerHTML=rows.map(([a,b,c])=>`<div class="mini-row"><span>${a}</span><b class="${c}">${b}</b></div>`).join("")}
function renderStatusSummary(){const map={};db.entregas.forEach(d=>{const s=norm(d.Status)||"Sem status";map[s]=(map[s]||0)+1});const rows=Object.keys(map).sort().map(k=>`<div class="mini-row"><span>${escapeHtml(k)}</span><b>${map[k]}</b></div>`).join("");document.getElementById("statusSummary").innerHTML=rows||'<p class="muted">Nenhuma entrega encontrada.</p>'}
function statusBadge(status){const s=norm(status);if(s==="Entrega finalizada")return'<span class="badge green">Entrega finalizada</span>';if(s==="Cancelada"||s==="Cancelada Geral")return`<span class="badge red">${escapeHtml(s)}</span>`;if(s==="Aguardando entregador")return'<span class="badge yellow">Aguardando entregador</span>';if(s==="Entrega aceita")return'<span class="badge purple">Entrega aceita</span>';return`<span class="badge">${escapeHtml(s||"Sem status")}</span>`}function paymentBadge(status){const s=norm(status)||"Aguardando confirmação";if(s==="Pago")return'<span class="badge green">Pago</span>';if(s==="Pendente")return'<span class="badge red">Pendente</span>';return`<span class="badge yellow">${escapeHtml(s)}</span>`}function waLink(v){const d=onlyDigits(v);if(!d)return"-";return`<a target="_blank" href="https://wa.me/55${d}">${escapeHtml(v)}</a>`}

function whatsappCobranca(nome,whatsapp,valor){const d=onlyDigits(whatsapp);if(!d){alert("WhatsApp não cadastrado para enviar cobrança.");return}const msg=`COBRANÇA DO DIA PEGA E LEVA - OLÁ ${norm(nome)||"CLIENTE"} PASSANDO PARA AVISAR DO PAGAMENTO DAS ENTREGAS DO DIA NO VALOR DE ${money(num(valor))} E AS INFORMAÇÕES PARA PAGEMENTO CHAVE PIX: 57293143000156 - BANCO MERCADO PAGO MARLLUS VINICIUS S ARAUJO`;window.open(`https://web.whatsapp.com/send?phone=55${d}&text=${encodeURIComponent(msg)}`,"_blank")}
async function apiPost(payload){if(!APP_SCRIPT_URL||APP_SCRIPT_URL.includes("COLE_AQUI"))throw new Error("Cole a URL do Apps Script Web App em APP_SCRIPT_URL no painel.");const res=await fetch(APP_SCRIPT_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({ok:false,error:"Resposta inválida do Apps Script."}));if(!data.ok)throw new Error(data.error||"Ação não concluída.");return data}
let pendingDebtPayment=null;
function openDebtPaymentModal(tipo,codigo,nome,id,valor){if(!codigo&&!id)return alert("Cadastro sem ID ou código de acesso.");pendingDebtPayment={tipo,codigo,nome,id,valor:num(valor)};const body=document.getElementById("debtPaymentModalBody");if(body)body.innerHTML=`<div class="mini-row"><span>Cadastro</span><b>${escapeHtml(nome||"Cliente/empresa")}</b></div><div class="mini-row"><span>Tipo</span><b>${tipo==="empresa"?"Empresa":"Usuário"}</b></div><div class="mini-row"><span>Valor pendente</span><b class="money red">${money(num(valor))}</b></div><p class="muted">Ao confirmar, o valor pendente será lançado como pago, o PagamentoPendente será zerado e, no caso de empresa, o SaldoDevedor também será abatido.</p>`;document.getElementById("debtPaymentModal").classList.add("active")}
function closeDebtPaymentModal(){document.getElementById("debtPaymentModal").classList.remove("active");pendingDebtPayment=null}
async function confirmDebtPayment(){const p=pendingDebtPayment;if(!p)return;showLoader("Atualizando pagamento do devedor...");try{await apiPost({action:"adminClearPending",tipo:p.tipo,codigo:p.codigo,id:p.id});showStatus("Pagamento atualizado como pago e débito zerado com sucesso.","green");closeDebtPaymentModal();await loadDashboard(true)}catch(err){showStatus(err.message||String(err),"red")}finally{hideLoader()}}
async function quitarPendente(tipo,codigo,nome,id){const item=(tipo==="empresa"?db.empresas:db.usuarios).find(x=>norm(x.ID)===norm(id)||norm(x.CodigoAcesso)===norm(codigo));openDebtPaymentModal(tipo,codigo,nome,id,item?num(item.PagamentoPendente):0)}
async function cadastrarEntregador(){const p={action:"adminRegisterDriver",nome:norm(document.getElementById("driverNome").value),whatsapp:norm(document.getElementById("driverWhatsApp").value),cpf:norm(document.getElementById("driverCPF").value),placaMoto:norm(document.getElementById("driverPlaca").value),codigo:norm(document.getElementById("driverCodigo").value),email:norm(document.getElementById("driverEmail").value)};if(!p.nome||!p.whatsapp||!p.cpf||!p.placaMoto||!p.codigo||!p.email)return alert("Preencha todos os dados do entregador.");showLoader("Cadastrando entregador...");try{await apiPost(p);["driverNome","driverWhatsApp","driverCPF","driverPlaca","driverCodigo","driverEmail"].forEach(id=>document.getElementById(id).value="");showStatus("Entregador cadastrado com sucesso.","green");await loadDashboard(false)}catch(err){showStatus(err.message||String(err),"red")}finally{hideLoader()}}
async function cadastrarEmpresa(){const p={action:"adminRegisterCompany",responsavel:norm(document.getElementById("empresaResponsavel").value),whatsapp:norm(document.getElementById("empresaWhatsApp").value),cpfCnpj:norm(document.getElementById("empresaCpfCnpj").value),codigo:norm(document.getElementById("empresaCodigo").value),email:norm(document.getElementById("empresaEmail").value),rua:norm(document.getElementById("empresaRua").value),numero:norm(document.getElementById("empresaNumero").value),referencia:norm(document.getElementById("empresaReferencia").value),cidade:norm(document.getElementById("empresaCidade").value)};if(!p.responsavel||!p.whatsapp||!p.cpfCnpj||!p.codigo||!p.email||!p.rua||!p.numero||!p.referencia||!p.cidade)return alert("Preencha todos os dados da empresa.");showLoader("Cadastrando empresa...");try{await apiPost(p);["empresaResponsavel","empresaWhatsApp","empresaCpfCnpj","empresaCodigo","empresaEmail","empresaRua","empresaNumero","empresaReferencia"].forEach(id=>document.getElementById(id).value="");document.getElementById("empresaCidade").value="Uruçuí";showStatus("Empresa cadastrada com sucesso.","green");await loadDashboard(false)}catch(err){showStatus(err.message||String(err),"red")}finally{hideLoader()}}
function acoesCobranca(tipo,codigo,nome,whatsapp,valor,id){const v=num(valor);if(v<=0)return'<span class="muted">Quitado</span>';return`<div class="action-stack"><button class="mini-btn blue" onclick="whatsappCobranca('${escapeHtml(String(nome)).replace(/'/g,"&#039;")}','${escapeHtml(String(whatsapp)).replace(/'/g,"&#039;")}',${v})"><i class="fa-brands fa-whatsapp"></i> Cobrar</button><button class="mini-btn green" onclick="openDebtPaymentModal('${tipo}','${escapeHtml(String(codigo)).replace(/'/g,"&#039;")}','${escapeHtml(String(nome)).replace(/'/g,"&#039;")}','${escapeHtml(String(id||"")).replace(/'/g,"&#039;")}',${v})"><i class="fa-solid fa-check"></i> Marcar pago</button></div>`}


function deliveryKey(d){return norm(d.ID)||[norm(d.CriadoEm),norm(d.NomeSolicitante),norm(d.BairroColeta),norm(d.BairroDestino),norm(d.Valor)].join("|")}
function checkNewDeliveries(){const ids=db.entregas.map(deliveryKey).filter(Boolean);const oldRaw=localStorage.getItem("pegaleva_known_deliveries");if(!oldRaw){localStorage.setItem("pegaleva_known_deliveries",JSON.stringify(ids));return}let old=[];try{old=JSON.parse(oldRaw)||[]}catch(e){old=[]}const oldSet=new Set(old);const novas=db.entregas.filter(d=>!oldSet.has(deliveryKey(d)));if(novas.length){const list=novas.slice().reverse();deliveryNotifications=[...list.map(d=>({id:deliveryKey(d),title:"NOVA ENTREGA",text:`${norm(d.NomeSolicitante)||"Cliente"} • ${norm(d.BairroColeta)||"-"} → ${norm(d.BairroDestino)||"-"} • ${money(num(d.Valor))}`,time:new Date().toLocaleString("pt-BR")})),...deliveryNotifications].slice(0,30);showNewDeliveryAlert(list[0],novas.length)}localStorage.setItem("pegaleva_known_deliveries",JSON.stringify(ids))}
function renderChatNotifications(){const pendentes=(db.saques||[]).filter(s=>lower(s.Status)!=="pago").slice().reverse();document.getElementById("chatCount").innerText=pendentes.length;document.getElementById("chatList").innerHTML=pendentes.length?pendentes.map(s=>`<div class="chat-item"><strong><i class="fa-solid fa-money-bill-transfer"></i> ${escapeHtml(s.NomeEntregador||"Entregador")}</strong><p><b>Valor que deve ser transferido:</b> ${money(num(s.ValorSolicitado))}<br><span class="badge yellow">Em progresso de transferência</span><br><b>Chave PIX:</b> ${escapeHtml(s.ChavePix||"")}<br><b>Nome do destinatário:</b> ${escapeHtml(s.NomeDestinatario||"")}<br><b>Código:</b> ${escapeHtml(s.CodigoEntregador||"")}<br><span class="muted">Valor já descontado da taxa de sistema/serviço de R$1,98 por entrega.</span></p><small>${escapeHtml(s.CriadoEm||"")}</small><button class="mini-btn green" style="margin-top:8px" onclick="payWithdraw('${escapeHtml(String(s.ID)).replace(/'/g,"&#039;")}')"><i class="fa-solid fa-check"></i> PAGO!</button></div>`).join(""):'<p class="muted">Nenhuma cobrança/saque pendente.</p>'}
function toggleSideChat(force){const el=document.getElementById("sideChat");if(force===false)el.classList.remove("active");else if(force===true)el.classList.add("active");else el.classList.toggle("active")}
function openPayWithdrawModal(id){if(!id)return;currentPayWithdrawId=id;const s=(db.saques||[]).find(x=>String(x.ID)===String(id))||{};document.getElementById("payWithdrawModalBody").innerHTML=`<div class="mini-row"><span>Entregador</span><b>${escapeHtml(s.NomeEntregador||"Entregador")}</b></div><div class="mini-row"><span>Valor do saque</span><b class="money green">${money(num(s.ValorSolicitado))}</b></div><div class="mini-row"><span>PIX</span><b>${escapeHtml(s.ChavePix||"-")}</b></div><div class="mini-row"><span>Destinatário</span><b>${escapeHtml(s.NomeDestinatario||"-")}</b></div><div class="mini-row"><span>Ação</span><b>Marcar como PAGO e remover apenas o valor solicitado do saldo do entregador.</b></div>`;document.getElementById("payWithdrawModal").classList.add("active")}function closePayWithdrawModal(){document.getElementById("payWithdrawModal").classList.remove("active");currentPayWithdrawId=""}async function confirmPayWithdraw(){const id=currentPayWithdrawId;if(!id)return;closePayWithdrawModal();showLoader("Confirmando pagamento...");try{await apiPost({action:"adminPayDriverWithdraw",id});showStatus("Saque marcado como pago e saldo do entregador atualizado.","green");await loadDashboard(false)}catch(err){showStatus(err.message||String(err),"red")}finally{hideLoader()}}async function payWithdraw(id){openPayWithdrawModal(id)}
function unlockAlertAudio(){try{alertAudioCtx=alertAudioCtx||new (window.AudioContext||window.webkitAudioContext)();if(alertAudioCtx.state==="suspended")alertAudioCtx.resume()}catch(e){}}
function beepOnce(){try{unlockAlertAudio();const now=alertAudioCtx.currentTime;[740,980,1240].forEach((freq,i)=>{const osc=alertAudioCtx.createOscillator();const gain=alertAudioCtx.createGain();osc.type="square";osc.frequency.value=freq;gain.gain.setValueAtTime(.001,now+i*.12);gain.gain.exponentialRampToValueAtTime(.75,now+i*.12+.03);gain.gain.exponentialRampToValueAtTime(.001,now+i*.12+.22);osc.connect(gain);gain.connect(alertAudioCtx.destination);osc.start(now+i*.12);osc.stop(now+i*.12+.24)})}catch(e){}}
function startAlertSound(){stopAlertSound();beepOnce();alertSoundTimer=setInterval(beepOnce,650)}
function stopAlertSound(){if(alertSoundTimer){clearInterval(alertSoundTimer);alertSoundTimer=null}}
function showNewDeliveryAlert(d,total){document.getElementById("newDeliveryAlertText").innerText=total>1?`${total} novas entregas apareceram no dashboard.`:`${norm(d.NomeSolicitante)||"Cliente"} solicitou uma nova entrega: ${norm(d.BairroColeta)||"-"} → ${norm(d.BairroDestino)||"-"}.`;document.getElementById("newDeliveryAlert").classList.add("active");startAlertSound();renderChatNotifications()}
function confirmNewDeliveryAlert(){stopAlertSound();document.getElementById("newDeliveryAlert").classList.remove("active")}
function deliveryRow(d){return `<tr><td><b>${escapeHtml(d.ID)}</b></td><td>${dateBR(d.CriadoEm)}</td><td><b>${escapeHtml(d.NomeSolicitante)}</b><br><span class="muted">${escapeHtml(d.TipoCliente)} • ${escapeHtml(d.CodigoCliente)}</span><br>${waLink(d.WhatsAppSolicitante)}</td><td>${escapeHtml(d.BairroColeta)} → ${escapeHtml(d.BairroDestino)}<br><span class="muted">${escapeHtml(d.EnderecoColeta)} / ${escapeHtml(d.EnderecoDestino)}</span></td><td>${escapeHtml(d.NomeEntregador||"-")}<br><span class="muted">Placa: ${escapeHtml(d.PlacaMoto||"-")}</span></td><td>${statusBadge(d.Status)}</td><td>${paymentBadge(d.StatusPagamento)}</td><td><b class="money">${money(num(d.Valor))}</b></td><td>${dateBR(d.AtualizadoEm||"")}</td></tr>`}
function openDeliveriesModal(){renderDeliveriesModal();document.getElementById("deliveriesModal").classList.add("active")}
function closeDeliveriesModal(){document.getElementById("deliveriesModal").classList.remove("active")}
function renderDeliveriesModal(){document.getElementById("deliveriesModalTable").innerHTML=(currentDeliveryExport||[]).map(deliveryRow).join("")||'<tr><td colspan="9" class="muted">Nenhuma entrega encontrada.</td></tr>'}
function renderDeliveries(){const q=lower(document.getElementById("deliverySearch").value);const st=norm(document.getElementById("deliveryStatusFilter").value);const pay=norm(document.getElementById("deliveryPaymentFilter").value);const dateMode=norm(document.getElementById("deliveryDateFilter").value);const selected=document.getElementById("salesDate").value;let list=db.entregas.filter(d=>{const text=lower(Object.values(d).join(" "));const dateOk=dateMode!=="selected"||!selected||dateISO(d.CriadoEm||d.AtualizadoEm)===selected;return(!q||text.includes(q))&&(!st||norm(d.Status)===st)&&(!pay||norm(d.StatusPagamento)===pay)&&dateOk}).slice().reverse();currentDeliveryExport=list;const preview=list.slice(0,4);document.getElementById("deliveriesTable").innerHTML=preview.map(deliveryRow).join("")||'<tr><td colspan="9" class="muted">Nenhuma entrega encontrada.</td></tr>';if(document.getElementById("deliveriesModal").classList.contains("active"))renderDeliveriesModal()}
function userRow(u){return `<tr><td>${escapeHtml(u.ID)}</td><td><b>${escapeHtml(u.Nome)}</b><br><span class="muted">${dateBR(u.CriadoEm)}</span></td><td>${waLink(u.WhatsApp)}</td><td>${escapeHtml(u.Email)}</td><td>${escapeHtml(u.CPF)}</td><td><b>${escapeHtml(u.CodigoAcesso)}</b></td><td><b>${num(u.EntregasSolicitadas)}</b></td><td><b class="money green">${money(num(u.ValorPago))}</b></td><td><b class="money red">${money(num(u.PagamentoPendente))}</b></td><td>${acoesCobranca("usuario",u.CodigoAcesso,u.Nome,u.WhatsApp,u.PagamentoPendente,u.ID)}</td></tr>`}
function openUsersModal(){renderUsersModal();document.getElementById("usersModal").classList.add("active")}
function closeUsersModal(){document.getElementById("usersModal").classList.remove("active")}
function renderUsersModal(){document.getElementById("usersModalTable").innerHTML=(currentUsersList||[]).map(userRow).join("")||'<tr><td colspan="10" class="muted">Nenhum usuário encontrado.</td></tr>'}
function renderUsers(){const q=lower(document.getElementById("userSearch").value);const list=db.usuarios.filter(u=>!q||lower(Object.values(u).join(" ")).includes(q)).slice().reverse();currentUsersList=list;document.getElementById("usersTable").innerHTML=list.slice(0,4).map(userRow).join("")||'<tr><td colspan="10" class="muted">Nenhum usuário encontrado.</td></tr>';if(document.getElementById("usersModal").classList.contains("active"))renderUsersModal()}
function companyRow(e){return `<tr><td>${escapeHtml(e.ID)}</td><td><b>${escapeHtml(e.Responsavel)}</b><br><span class="muted">${dateBR(e.CriadoEm)}</span></td><td>${waLink(e.WhatsApp)}</td><td>${escapeHtml(e.Email)}</td><td>${escapeHtml(e.CPF_CNPJ)}</td><td>${escapeHtml(e.Endereco||[e.Rua,e.Numero,e.Referencia,e.Cidade].filter(Boolean).join(", "))}</td><td><b>${escapeHtml(e.CodigoAcesso)}</b></td><td><b class="money red">${money(num(e.SaldoDevedor))}</b></td><td><b class="money green">${money(num(e.ValorPago))}</b></td><td><b class="money red">${money(num(e.PagamentoPendente))}</b></td><td>${priorityBadge(e.Prioridade)}</td><td>${acoesCobranca("empresa",e.CodigoAcesso,e.Responsavel,e.WhatsApp,e.PagamentoPendente,e.ID)}</td></tr>`}
function openCompaniesModal(){renderCompaniesModal();document.getElementById("companiesModal").classList.add("active")}
function closeCompaniesModal(){document.getElementById("companiesModal").classList.remove("active")}
function renderCompaniesModal(){document.getElementById("companiesModalTable").innerHTML=(currentCompaniesList||[]).map(companyRow).join("")||'<tr><td colspan="12" class="muted">Nenhuma empresa encontrada.</td></tr>'}
function renderCompanies(){const q=lower(document.getElementById("companySearch").value);const list=db.empresas.filter(e=>!q||lower(Object.values(e).join(" ")).includes(q)).slice().reverse();currentCompaniesList=list;document.getElementById("companiesTable").innerHTML=list.slice(0,4).map(companyRow).join("")||'<tr><td colspan="12" class="muted">Nenhuma empresa encontrada.</td></tr>';if(document.getElementById("companiesModal").classList.contains("active"))renderCompaniesModal()}
function priorityBadge(v){const s=norm(v)||"Não";const active=["sim","ativo","alta","prioridade"].includes(lower(s));return active?`<span class="badge purple">${escapeHtml(s)}</span>`:`<span class="badge gray">${escapeHtml(s)}</span>`}

function driverDeliveries(driver){const codigo=norm(driver.CodigoAcesso);const nome=lower(driver.Nome);const placa=lower(driver.PlacaMoto);return db.entregas.filter(e=>{const cods=[e.CodigoEntregador,e.CodigoMotorista,e.EntregadorCodigo,e.CodigoAcessoEntregador].map(norm).filter(Boolean);const nomes=[e.NomeEntregador,e.Entregador,e.Motorista].map(lower).filter(Boolean);const placas=[e.PlacaMoto,e.PlacaEntregador].map(lower).filter(Boolean);return(codigo&&cods.includes(codigo))||(nome&&nomes.includes(nome))||(placa&&placas.includes(placa))})}
function driverSummaryMonthDefault(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function monthLabel(v){if(!v)return"";const[a,b]=v.split("-");return `${b}/${a}`}
function openDriverSummaryModal(id){const driver=db.entregadores.find(d=>norm(d.ID)===norm(id));if(!driver){alert("Entregador não encontrado.");return}currentDriverSummary=driver;document.getElementById("driverSummaryTitle").innerText=`Resumo do entregador - ${norm(driver.Nome)||"Sem nome"}`;document.getElementById("driverSummaryMonth").value=driverSummaryMonthDefault();document.getElementById("driverSummaryModal").classList.add("active");renderDriverSummaryModal()}
function closeDriverSummaryModal(){document.getElementById("driverSummaryModal").classList.remove("active")}
function getDriverMonthSummary(){const driver=currentDriverSummary;if(!driver)return{driver:null,month:"",list:[],total:0,empresa:0,entregador:0};const month=document.getElementById("driverSummaryMonth").value||driverSummaryMonthDefault();const list=driverDeliveries(driver).filter(e=>norm(e.Status)==="Entrega finalizada"&&dateISO(e.CriadoEm||e.AtualizadoEm).slice(0,7)===month).slice().sort((a,b)=>(parseDate(a.CriadoEm||a.AtualizadoEm)||0)-(parseDate(b.CriadoEm||b.AtualizadoEm)||0));const total=list.reduce((s,e)=>s+num(e.Valor),0);const empresa=list.length*1.98;const entregador=total-empresa;return{driver,month,list,total,empresa,entregador}}
function renderDriverSummaryModal(){const s=getDriverMonthSummary();if(!s.driver)return;document.getElementById("driverSummaryContent").innerHTML=`<div class="driver-summary-grid"><div class="summary-box"><small>Entregas no mês</small><b>${s.list.length}</b></div><div class="summary-box"><small>Valor faturado</small><b class="money">${money(s.total)}</b></div><div class="summary-box"><small>Valor da empresa</small><b class="money red">${money(s.empresa)}</b><p class="muted">R$1,98 por entrega</p></div><div class="summary-box"><small>Valor da fatura</small><b class="money green">${money(s.entregador)}</b></div></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>ID</th><th>Cliente</th><th>Rota</th><th>Status</th><th>Valor</th><th>Empresa</th><th>Fatura</th></tr></thead><tbody>${s.list.map(e=>`<tr><td>${dateBR(e.CriadoEm||e.AtualizadoEm)}</td><td><b>${escapeHtml(e.ID)}</b></td><td>${escapeHtml(e.NomeSolicitante||"")}</td><td>${escapeHtml(e.BairroColeta||"")} → ${escapeHtml(e.BairroDestino||"")}</td><td>${statusBadge(e.Status)}</td><td><b class="money">${money(num(e.Valor))}</b></td><td><b class="money red">${money(1.98)}</b></td><td><b class="money green">${money(num(e.Valor)-1.98)}</b></td></tr>`).join("")||'<tr><td colspan="8" class="muted">Nenhuma entrega encontrada para este mês.</td></tr>'}</tbody></table></div>`}
function generateDriverInvoice(){const s=getDriverMonthSummary();if(!s.driver)return;const rows=s.list.map(e=>`<tr><td>${dateBR(e.CriadoEm||e.AtualizadoEm)}</td><td>${escapeHtml(e.ID)}</td><td>${escapeHtml(e.NomeSolicitante||"")}</td><td>${escapeHtml(e.BairroColeta||"")} → ${escapeHtml(e.BairroDestino||"")}</td><td>${money(num(e.Valor))}</td><td>${money(1.98)}</td><td>${money(num(e.Valor)-1.98)}</td></tr>`).join("")||'<tr><td colspan="7">Nenhuma entrega encontrada.</td></tr>';const html=`<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Fatura - ${escapeHtml(s.driver.Nome)}</title><style>body{font-family:Arial,sans-serif;color:#0f172a;padding:28px}h1{margin:0 0 8px}p{margin:5px 0;color:#475569}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.card{border:1px solid #e5edf8;border-radius:14px;padding:12px}.card small{display:block;color:#64748b;font-weight:bold}.card b{font-size:20px}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{border-bottom:1px solid #e5edf8;padding:10px;text-align:left;font-size:13px}th{background:#f8fbff}.total{margin-top:18px;text-align:right;font-size:22px;font-weight:bold}@media print{button{display:none}}</style></head><body><button onclick="window.print()">Imprimir / Salvar PDF</button><h1>Fatura do entregador</h1><p><b>Entregador:</b> ${escapeHtml(s.driver.Nome||"")}</p><p><b>Mês:</b> ${monthLabel(s.month)}</p><p><b>Gerada em:</b> ${new Date().toLocaleString("pt-BR")}</p><div class="cards"><div class="card"><small>Entregas</small><b>${s.list.length}</b></div><div class="card"><small>Valor faturado</small><b>${money(s.total)}</b></div><div class="card"><small>Valor da empresa</small><b>${money(s.empresa)}</b></div><div class="card"><small>Valor da fatura</small><b>${money(s.entregador)}</b></div></div><table><thead><tr><th>Data</th><th>ID</th><th>Cliente</th><th>Rota</th><th>Valor</th><th>Empresa</th><th>Fatura</th></tr></thead><tbody>${rows}</tbody></table><div class="total">Valor da fatura: ${money(s.entregador)}</div></body></html>`;const w=window.open("","_blank");w.document.write(html);w.document.close()}

function driverRow(d){const f=driverFinancial(d);return `<tr><td>${escapeHtml(d.ID)}</td><td><b>${escapeHtml(d.Nome)}</b><br><span class="muted">${dateBR(d.CriadoEm)}</span></td><td>${waLink(d.WhatsApp)}</td><td>${escapeHtml(d.Email)}</td><td>${escapeHtml(d.CPF)}</td><td>${escapeHtml(d.PlacaMoto)}</td><td><b>${escapeHtml(d.CodigoAcesso)}</b></td><td>${lower(d.Ativo)==="ativo"?'<span class="badge green">Ativo</span>':'<span class="badge red">Inativo</span>'}</td><td><b class="money">${money(f.total)}</b><br><span class="muted">${f.entregas} entregas</span></td><td><b class="money red">${money(f.taxa)}</b><br><span class="muted">R$1,98 por entrega</span></td><td><b class="money green">${money(f.saldo)}</b></td><td><b>${num(d.Curtidas)}</b></td><td><button class="mini-btn blue" onclick="openDriverSummaryModal('${escapeHtml(String(d.ID)).replace(/'/g,"&#039;")}')"><i class="fa-solid fa-file-invoice-dollar"></i> Resumo</button></td></tr>`}
function openDriversModal(){renderDriversModal();document.getElementById("driversModal").classList.add("active")}
function closeDriversModal(){document.getElementById("driversModal").classList.remove("active")}
function renderDriversModal(){document.getElementById("driversModalTable").innerHTML=(currentDriversList||[]).map(driverRow).join("")||'<tr><td colspan="13" class="muted">Nenhum entregador encontrado.</td></tr>'}
function renderDrivers(){const q=lower(document.getElementById("driverSearch").value);const st=lower(document.getElementById("driverStatusFilter").value);const list=db.entregadores.filter(d=>{const active=lower(d.Ativo)==="ativo"?"ativo":"inativo";return(!q||lower(Object.values(d).join(" ")).includes(q))&&(!st||active===st)}).slice().reverse();currentDriversList=list;document.getElementById("driversTable").innerHTML=list.slice(0,4).map(driverRow).join("")||'<tr><td colspan="13" class="muted">Nenhum entregador encontrado.</td></tr>';if(document.getElementById("driversModal").classList.contains("active"))renderDriversModal()}
function renderMessages(){const q=lower(document.getElementById("messageSearch").value);const list=(db.mensagens||[]).filter(m=>!q||lower(Object.values(m).join(" ")).includes(q)).slice().reverse();document.getElementById("messagesTable").innerHTML=list.map(m=>`<tr><td>${escapeHtml(m.ID)}</td><td>${dateBR(m.CriadoEm)}</td><td><b>${escapeHtml(m.EntregaID)}</b></td><td>${escapeHtml(m.CodigoCliente)}</td><td>${escapeHtml(m.CodigoEntregador)}</td><td>${escapeHtml(m.RemetenteTipo)}</td><td>${escapeHtml(m.Mensagem)}</td><td>${norm(m.LidaCliente).toLowerCase()==="sim"?'<span class="badge green">Sim</span>':'<span class="badge yellow">Não</span>'}</td><td>${norm(m.LidaEntregador).toLowerCase()==="sim"?'<span class="badge green">Sim</span>':'<span class="badge yellow">Não</span>'}</td></tr>`).join("")||'<tr><td colspan="9" class="muted">Nenhuma mensagem encontrada.</td></tr>'}
document.addEventListener("click",unlockAlertAudio,{once:true});
function exportCSV(){const rows=currentDeliveryExport||[];if(!rows.length){alert("Nenhuma entrega filtrada para exportar.");return}const headers=Object.keys(rows[0]);const csv=[headers.join(","),...rows.map(r=>headers.map(h=>`"${String(r[h]??"").replace(/"/g,'""')}"`).join(","))].join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="pegaleva_entregas_filtradas.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}

function toggleAdminTools(){document.getElementById("adminToolsFloat").classList.toggle("active")}
function openCouponTool(){document.getElementById("couponToolModal").classList.add("active")}
function closeCouponTool(){document.getElementById("couponToolModal").classList.remove("active")}
function openAnnouncementTool(){document.getElementById("announcementToolModal").classList.add("active")}
function closeAnnouncementTool(){document.getElementById("announcementToolModal").classList.remove("active")}
async function sendCouponTool(){
  const cupom=norm(document.getElementById("toolCouponName").value).toUpperCase();
  const percentual=num(document.getElementById("toolCouponPercent").value);
  if(!cupom||!percentual)return showStatus("Preencha o nome do cupom e o percentual.","red");
  showLoader("Cadastrando cupom...");
  try{
    await apiPost({action:"adminCreateCoupon",cupom,percentual});
    document.getElementById("toolCouponName").value="";
    document.getElementById("toolCouponPercent").value="";
    closeCouponTool();
    showStatus("Cupom cadastrado com sucesso na aba PRICE.","green");
  }catch(err){showStatus(err.message||String(err),"red")}finally{hideLoader()}
}
async function sendAnnouncementTool(){
  const titulo=norm(document.getElementById("toolAnnouncementTitle").value)||"Comunicado PegaLeva";
  const mensagem=norm(document.getElementById("toolAnnouncementMsg").value);
  if(!mensagem)return showStatus("Digite o comunicado.","red");
  showLoader("Enviando comunicado...");
  try{
    await apiPost({action:"adminSendAnnouncement",titulo,mensagem});
    document.getElementById("toolAnnouncementTitle").value="";
    document.getElementById("toolAnnouncementMsg").value="";
    closeAnnouncementTool();
    showStatus("Comunicado enviado para usuários e empresas por 24H.","green");
  }catch(err){showStatus(err.message||String(err),"red")}finally{hideLoader()}
}

